import { CompanionSuggestion, Mood } from "@/types";

/**
 * Small, hand-written dataset the companion picks from. Every string
 * here is original — none of this is generated by a live model (see
 * DISCLAIMERS.companionNotRealAI). Keep entries short, warm, and
 * non-clinical; anything that sounds like a diagnosis or a directive
 * belongs in the screening/counseling flows, not here.
 */
export const MOOD_REFLECTIONS: Record<Mood, { fa: string; en: string }[]> = {
  sad: [
    { fa: "شنیدم. حق داری این حس رو داشته باشی، و لازم نیست الان خوب باشی.", en: "I hear you. You're allowed to feel this way, and you don't have to be okay right now." },
    { fa: "بعضی روزها همین‌طورن. کنارتم تا این یکی رو هم رد کنی.", en: "Some days are just like that. I'm here while you get through this one too." },
  ],
  anxious: [
    { fa: "به‌نظر می‌رسه ذهنت الان شلوغه. یک نفس عمیق بکش؛ من همین‌جام.", en: "It sounds like your mind is racing right now. Take one deep breath — I'm right here." },
    { fa: "نگرانی‌ات معتبره. قدم‌به‌قدم پیش می‌ریم.", en: "Your worry is valid. We'll take it one step at a time." },
  ],
  angry: [
    { fa: "به‌نظر می‌رسه چیزی واقعاً اذیتت کرده. عصبانیتت رو می‌فهمم.", en: "It sounds like something really got to you. Your anger makes sense." },
    { fa: "حق داری عصبانی باشی. لازم نیست فوراً آرام باشی.", en: "You're allowed to be angry. You don't have to calm down immediately." },
  ],
  numb: [
    { fa: "بعضی وقت‌ها بی‌حسی هم خودش یک جور احساسه. لازم نیست الان چیزی رو توضیح بدی.", en: "Sometimes numbness is its own kind of feeling. You don't have to explain anything right now." },
    { fa: "همین که اینجایی و باهام حرف می‌زنی، به‌اندازهٔ کافی هست.", en: "Just being here and talking to me is enough for now." },
  ],
  overwhelmed: [
    { fa: "به‌نظر می‌رسه همه‌چیز روی هم ریخته. لازم نیست همه‌اش رو همین الان حل کنیم.", en: "It sounds like everything is piling up. We don't have to solve all of it right now." },
    { fa: "یکی‌یکی بریم جلو؛ همین الان فقط با یک نفس شروع کن.", en: "Let's go one thing at a time; right now, just start with one breath." },
  ],
  lonely: [
    { fa: "تنهایی سخته. همین الان من اینجام و به حرف‌هات گوش می‌دم.", en: "Loneliness is hard. Right now, I'm here and I'm listening." },
    { fa: "حتی وقتی حس می‌کنی کسی نیست، این حس واقعیت کامل رو نشون نمی‌ده.", en: "Even when it feels like no one's there, that feeling doesn't show the whole picture." },
  ],
  hopeful: [
    { fa: "خوشحالم که امروز حس امید داری. این حس رو قدر بدون.", en: "I'm glad you're feeling hopeful today. Hold onto that." },
    { fa: "این انرژی خوب رو با خودت نگه دار؛ لیاقتش رو داری.", en: "Keep that good energy with you; you deserve it." },
  ],
  calm: [
    { fa: "چه خوب که امروز آرومی. امیدوارم این حس ادامه پیدا کنه.", en: "It's great that you're feeling calm today. I hope it lasts." },
    { fa: "این لحظه‌های آرامش رو برای خودت نگه دار.", en: "Hold onto these calm moments for yourself." },
  ],
};

export const JOURNAL_ACKNOWLEDGMENTS: { fa: string; en: string }[] = [
  { fa: "ممنون که این رو با من در میون گذاشتی.", en: "Thank you for sharing that with me." },
  { fa: "شنیدمت. حرف‌هات برام مهمه.", en: "I hear you. What you're saying matters to me." },
  { fa: "خوشحالم که به‌جای نگه‌داشتنش تو دلت، نوشتیش.", en: "I'm glad you got that out instead of holding it in." },
  { fa: "هر وقت خواستی بیشتر بگی، من اینجام.", en: "Whenever you want to say more, I'm here." },
];

const suggestion = (kind: CompanionSuggestion["kind"], fa: string, en: string): CompanionSuggestion => ({
  kind,
  label: { fa, en },
});

export const MOOD_SUGGESTIONS: Record<Mood, CompanionSuggestion[]> = {
  sad: [
    suggestion("music", "یک موسیقی آرام‌بخش برایت پخش کنم؟", "Want me to play some calming music?"),
    suggestion("screening", "دوست داری یک گفتگوی کوتاه دربارهٔ حالت داشته باشیم؟", "Want to have a short check-in conversation about how you're doing?"),
  ],
  anxious: [
    suggestion("music", "یک موسیقی آرام برایت بگذارم تا کمی سبک شوی؟", "Should I play something calming to help you unwind a bit?"),
    suggestion("screening", "می‌خواهی چند سؤال کوتاه دربارهٔ این نگرانی بپرسم؟", "Want me to ask a few short questions about this worry?"),
  ],
  angry: [suggestion("music", "یک موسیقی برایت بگذارم تا این انرژی را خالی کنی؟", "Want some music to help you let that energy out?")],
  numb: [suggestion("favorite_music", "برویم موسیقی مورد علاقه‌ات را پیدا کنیم؟", "Want to go find some music you love?")],
  overwhelmed: [
    suggestion("music", "یک موسیقی آرام برایت پخش کنم تا کمی زمین‌گیر شوی؟", "Want some calming music to help you feel grounded?"),
    suggestion("fitness", "گاهی یک قدم‌زدن کوتاه کمک می‌کند؛ دوست داری راهنمایی ورزشی ببینی؟", "A short walk sometimes helps; want to see some activity suggestions?"),
  ],
  lonely: [
    suggestion("music", "بگذار یک موسیقی همراهت باشد.", "Let me put on some music to keep you company."),
    suggestion("counseling", "اگر موضوع دربارهٔ رابطه‌ای است، می‌توانم راهنمایی هم بدهم.", "If this is about a relationship, I can offer some guidance too."),
  ],
  hopeful: [suggestion("recipes", "بیا یک چیز خوشمزه با هم بپزیم تا این حس خوب را جشن بگیریم!", "Let's cook something delicious together to celebrate this good feeling!")],
  calm: [suggestion("storytelling", "اگر دوست داری، می‌توانم یک قصهٔ آرام برایت بگویم.", "If you'd like, I can tell you a calm story.")],
};

export const pickRandom = <T,>(arr: T[]): T => arr[Math.floor(Math.random() * arr.length)];
